-- Replaces the original 34-action strategy-doc register (CLAUDE.md Section 10.2) with the
-- 92-task, 5-week September production sprint from Staff Docs/All tasks sheet.xlsx (1 Sep - 30
-- Sep 2026). `on delete cascade` on task_activity.task_id (migration 0012) means each task's
-- activity history goes with it -- there is no separate cleanup step here.
--
-- Mapping notes:
--   * action_number: sheet's code verbatim, except "A16" (Claim software partner directories),
--     which repeats identically in all 5 weeks -- disambiguated here as A16-W1..A16-W5.
--   * category: sheet's Category column (new column added in migration 0013).
--   * position_responsible: sheet's Ownership text verbatim (e.g. "Tabish & Talha").
--   * assigned_to / co_assigned_to: first / second name in Ownership, resolved against profiles.
--   * due_date: end of that task's sprint week (Fri 4/11/18/25 Sep, Wed 30 Sep for week 5).
--   * quarter: 'Q1' for all rows (the whole sprint falls inside the Q1 window).
--   * status: defaults to 'pending' (sheet's "Not started").

delete from tasks;

insert into tasks (action_number, title, description, category, position_responsible, assigned_to, co_assigned_to, due_date, quarter, notes)
select 'S1', 'Internal Controls & SOX Compliance Services', 'Create parent & child pages with complete meta, H1/H2 structure, internal linking across SILO.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-04'::date, 'Q1', null
union all select 'S2', 'External Audit Support', 'Build service page with on-page SEO, schema markup, and cross-links to audit cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-04'::date, 'Q1', null
union all select 'S3', 'Internal Audit Support', 'Build service page with on-page SEO, schema markup, and cross-links to audit cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-04'::date, 'Q1', null
union all select 'S4', 'Audit Readiness Assessment', 'Build service page with on-page SEO, schema markup, and cross-links to audit cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-04'::date, 'Q1', null
union all select 'L1', 'Location Page — United Kingdom', 'Build UK-targeted location page with local schema, hreflang, UK-specific service messaging, and internal links.', 'Location Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-04'::date, 'Q1', null
union all select 'B1', 'New Blog 1', 'Research topic, draft, editorial QA via blog-review-seo skill, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-04'::date, 'Q1', null
union all select 'B2', 'New Blog 2', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-04'::date, 'Q1', null
union all select 'R1', 'Revamp Existing Blog 1', 'Audit current post, rewrite for AI Overviews / LLM citation, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-04'::date, 'Q1', null
union all select 'R2', 'Revamp Existing Blog 2', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-04'::date, 'Q1', null
union all select 'P1', 'Proofread Blog 1', 'Review draft from Lavi/Najma — check grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-04'::date, 'Q1', 'After B1 delivery'
union all select 'PB1', 'Publish Blog 1', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-04'::date, 'Q1', 'After P1 approval'
union all select 'D1', 'New blog image — Blog 1', 'Design featured image + in-post graphics for new Blog 1.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-04'::date, 'Q1', 'Deliver before publish'
union all select 'D2', 'New blog image — Blog 2', 'Design featured image + in-post graphics for new Blog 2.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-04'::date, 'Q1', null
union all select 'DR1', 'Revamp blog image — Blog 1', 'Update/replace featured image and in-post graphics for revamped Blog 1.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-04'::date, 'Q1', null
union all select 'DR2', 'Revamp blog image — Blog 2', 'Update/replace featured image and in-post graphics for revamped Blog 2.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-04'::date, 'Q1', null
union all select 'T1', 'Fix 404 errors', 'Crawl site with Screaming Frog / Ahrefs; identify all 404s; set up 301 redirects or restore pages.', 'Technical SEO', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-04'::date, 'Q1', 'Priority: fix broken UX first'
union all select 'A16-W1', 'Claim software partner directories', 'Complete partner/certification profiles: NetSuite, Sage Intacct, QuickBooks ProAdvisor, Xero Partner, Bill.com, Ramp, Brex.', 'Links', 'Syed Ali', (select id from profiles where full_name = 'Syed Ali'), null, '2026-09-04'::date, 'Q1', null
union all select 'O4', 'Industry / partner outreach', 'Begin outreach to industry contacts and potential partners for link-building and co-marketing.', 'Off-Page SEO', 'Talha', (select id from profiles where full_name = 'Talha Azeem'), null, '2026-09-04'::date, 'Q1', 'Continuous through Sep'
union all select 'S5', 'Internal Controls Design & Testing', 'Build service page with on-page SEO, link to SOX parent page, schema markup.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-11'::date, 'Q1', null
union all select 'S6', 'Accounts Payable Services', 'Create AP parent page with meta, internal links to AP child pages.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-11'::date, 'Q1', null
union all select 'S7', 'Invoice Processing & 3-Way Matching', 'Build child page under AP cluster with process-focused content and internal links.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-11'::date, 'Q1', null
union all select 'S8', 'Vendor Management Services', 'Build child page under AP cluster with vendor lifecycle content and internal links.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-11'::date, 'Q1', null
union all select 'L2', 'Location Page — Germany', 'Build Germany-targeted location page with local schema, hreflang, DE-specific messaging, and internal links.', 'Location Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-11'::date, 'Q1', null
union all select 'B3', 'New Blog 3', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-11'::date, 'Q1', null
union all select 'B4', 'New Blog 4', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-11'::date, 'Q1', null
union all select 'R3', 'Revamp Existing Blog 3', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'R4', 'Revamp Existing Blog 4', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'P2', 'Proofread Blog 2', 'Review draft from Lavi/Najma — check grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'PB2', 'Publish Blog 2', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'P3', 'Proofread Blog 3', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'PB3', 'Publish Blog 3', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-11'::date, 'Q1', null
union all select 'D3', 'New blog image — Blog 3', 'Design featured image + in-post graphics for new Blog 3.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-11'::date, 'Q1', null
union all select 'D4', 'New blog image — Blog 4', 'Design featured image + in-post graphics for new Blog 4.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-11'::date, 'Q1', null
union all select 'DR3', 'Revamp blog image — Blog 3', 'Update/replace featured image and in-post graphics for revamped Blog 3.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-11'::date, 'Q1', null
union all select 'DR4', 'Revamp blog image — Blog 4', 'Update/replace featured image and in-post graphics for revamped Blog 4.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-11'::date, 'Q1', null
union all select 'T2', 'Audit & fix redirects', 'Map all redirect chains and loops; consolidate to single-hop 301s; update internal links pointing to redirected URLs.', 'Technical SEO', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-11'::date, 'Q1', null
union all select 'W1', 'Service pages & location page publishing', 'Publish service pages with provided data, implement redirections, add metas, ctas, navbar/footer links update', 'Website', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-11'::date, 'Q1', null
union all select 'A16-W2', 'Claim software partner directories', 'Complete partner/certification profiles: NetSuite, Sage Intacct, QuickBooks ProAdvisor, Xero Partner, Bill.com, Ramp, Brex.', 'Links', 'Syed Ali', (select id from profiles where full_name = 'Syed Ali'), null, '2026-09-11'::date, 'Q1', null
union all select 'O1', 'Paid Guest Post 1', 'Identify target publication, pitch topic, write guest post with backlink, get published.', 'Off-Page SEO', 'Talha & Najma', (select id from profiles where full_name = 'Talha Azeem'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-11'::date, 'Q1', null
union all select 'S9', 'Accounts Receivable Services', 'Create AR parent page with meta, internal links to AR child pages.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-18'::date, 'Q1', null
union all select 'S10', 'Collections & Cash Application Services', 'Build child page under AR cluster with process content and links back to AR parent.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-18'::date, 'Q1', null
union all select 'S11', 'Payroll Services', 'Build standalone service page with full meta, schema, cross-links to finance ops cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-18'::date, 'Q1', null
union all select 'S12', 'AP & AR Automation Consulting', 'Build service page bridging AP/AR clusters; link to both parent pages.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-18'::date, 'Q1', null
union all select 'L3', 'Location Page — Switzerland', 'Build Switzerland-targeted location page with local schema, hreflang, CH-specific messaging.', 'Location Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-18'::date, 'Q1', null
union all select 'B5', 'New Blog 5', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-18'::date, 'Q1', null
union all select 'B6', 'New Blog 6', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-18'::date, 'Q1', null
union all select 'R5', 'Revamp Existing Blog 5', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'R6', 'Revamp Existing Blog 6', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'P4', 'Proofread Blog 4', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'PB4', 'Publish Blog 4', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'P5', 'Proofread Blog 5', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'PB5', 'Publish Blog 5', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-18'::date, 'Q1', null
union all select 'D5', 'New blog image — Blog 5', 'Design featured image + in-post graphics for new Blog 5.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-18'::date, 'Q1', null
union all select 'D6', 'New blog image — Blog 6', 'Design featured image + in-post graphics for new Blog 6.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-18'::date, 'Q1', null
union all select 'DR5', 'Revamp blog image — Blog 5', 'Update/replace featured image and in-post graphics for revamped Blog 5.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-18'::date, 'Q1', null
union all select 'DR6', 'Revamp blog image — Blog 6', 'Update/replace featured image and in-post graphics for revamped Blog 6.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-18'::date, 'Q1', null
union all select 'T3', 'Core Web Vitals optimization', 'Run Lighthouse / PageSpeed Insights; fix LCP, INP, CLS issues; compress images, defer JS, optimize CSS.', 'Technical SEO', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-18'::date, 'Q1', null
union all select 'W2', 'Service pages & location page publishing', 'Publish service pages with provided data, implement redirections, add metas, ctas, navbar/footer links update', 'Website', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-18'::date, 'Q1', null
union all select 'A16-W3', 'Claim software partner directories', 'Complete partner/certification profiles: NetSuite, Sage Intacct, QuickBooks ProAdvisor, Xero Partner, Bill.com, Ramp, Brex.', 'Links', 'Syed Ali', (select id from profiles where full_name = 'Syed Ali'), null, '2026-09-18'::date, 'Q1', null
union all select 'O3', 'PR Submission', 'Draft press release, submit to distribution service, track pickup and backlinks.', 'Off-Page SEO', 'Talha', (select id from profiles where full_name = 'Talha Azeem'), null, '2026-09-18'::date, 'Q1', null
union all select 'S13', 'Inventory Management Services', 'Build service page with supply chain focus, internal links to demand planning and trade promo pages.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-25'::date, 'Q1', null
union all select 'S14', 'Trade Promotions Management', 'Build child page under inventory/supply chain cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-25'::date, 'Q1', null
union all select 'S15', 'Demand & Supply Planning', 'Build child page under inventory/supply chain cluster.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-25'::date, 'Q1', null
union all select 'S16', 'Deductions & Chargeback Management', 'Build service page with deductions workflow content and links to AR/AP clusters.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-25'::date, 'Q1', null
union all select 'L4', 'Location Page — Sweden', 'Build Sweden-targeted location page with local schema, hreflang, SE-specific messaging.', 'Location Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-25'::date, 'Q1', null
union all select 'B7', 'New Blog 7', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-25'::date, 'Q1', null
union all select 'B8', 'New Blog 8', 'Research topic, draft, editorial QA, submit for proofreading.', 'New Blogs', 'Lavi & Najma', (select id from profiles where full_name = 'Lavi Shamoon'), (select id from profiles where full_name = 'Najma Furqan'), '2026-09-25'::date, 'Q1', null
union all select 'R7', 'Revamp Existing Blog 7', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'R8', 'Revamp Existing Blog 8', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'P6', 'Proofread Blog 6', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'PB6', 'Publish Blog 6', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'P7', 'Proofread Blog 7', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'PB7', 'Publish Blog 7', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-25'::date, 'Q1', null
union all select 'D7', 'New blog image — Blog 7', 'Design featured image + in-post graphics for new Blog 7.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-25'::date, 'Q1', null
union all select 'D8', 'New blog image — Blog 8', 'Design featured image + in-post graphics for new Blog 8.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-25'::date, 'Q1', null
union all select 'DR7', 'Revamp blog image — Blog 7', 'Update/replace featured image and in-post graphics for revamped Blog 7.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-25'::date, 'Q1', null
union all select 'DR8', 'Revamp blog image — Blog 8', 'Update/replace featured image and in-post graphics for revamped Blog 8.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-25'::date, 'Q1', null
union all select 'T4', 'Crawling & indexing fixes', 'Review robots.txt, crawl budget; check GSC index coverage; fix noindex tags, canonical issues; submit updated sitemap.', 'Technical SEO', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-25'::date, 'Q1', null
union all select 'W3', 'Service pages & location page publishing', 'Publish service pages with provided data, implement redirections, add metas, ctas, navbar/footer links update', 'Website', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-25'::date, 'Q1', null
union all select 'A16-W4', 'Claim software partner directories', 'Complete partner/certification profiles: NetSuite, Sage Intacct, QuickBooks ProAdvisor, Xero Partner, Bill.com, Ramp, Brex.', 'Links', 'Syed Ali', (select id from profiles where full_name = 'Syed Ali'), null, '2026-09-25'::date, 'Q1', null
union all select 'O2', 'Paid Guest Post 2', 'Identify target publication, pitch topic, write guest post with backlink, get published.', 'Off-Page SEO', 'Talha', (select id from profiles where full_name = 'Talha Azeem'), null, '2026-09-25'::date, 'Q1', null
union all select 'S17', 'Business Process Optimization', 'Build cross-cutting service page linking to multiple SILO clusters.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-30'::date, 'Q1', null
union all select 'S18', 'Finance System Implementation Support', 'Build service page with ERP/system focus, internal links across all relevant SILOs.', 'Service Pages', 'Tabish & Talha', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Talha Azeem'), '2026-09-30'::date, 'Q1', null
union all select 'R9', 'Revamp Existing Blog 9', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-30'::date, 'Q1', null
union all select 'R10', 'Revamp Existing Blog 10', 'Audit, rewrite for AEO/GEO, refresh meta, add internal links.', 'Blog Revamp', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-30'::date, 'Q1', null
union all select 'P8', 'Proofread Blog 8', 'Review draft — grammar, keyword placement, readability, SEO compliance.', 'Proofreading', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-30'::date, 'Q1', null
union all select 'PB8', 'Publish Blog 8', 'Final review, upload to CMS, set meta/schema, verify internal links, publish live.', 'Publishing', 'Tabish', (select id from profiles where full_name = 'Tabish Khalid'), null, '2026-09-30'::date, 'Q1', null
union all select 'DR9', 'Revamp blog image — Blog 9', 'Update/replace featured image and in-post graphics for revamped Blog 9.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-30'::date, 'Q1', null
union all select 'DR10', 'Revamp blog image — Blog 10', 'Update/replace featured image and in-post graphics for revamped Blog 10.', 'Design / Images', 'Hameed', (select id from profiles where full_name = 'Hameed Ishaq'), null, '2026-09-30'::date, 'Q1', null
union all select 'T5', 'Schema markup implementation', 'Implement JSON-LD structured data across service pages, location pages, and blog posts (Organization, Service, LocalBusiness, Article schemas).', 'Technical SEO', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-30'::date, 'Q1', 'After all new pages are live'
union all select 'A16-W5', 'Claim software partner directories', 'Complete partner/certification profiles: NetSuite, Sage Intacct, QuickBooks ProAdvisor, Xero Partner, Bill.com, Ramp, Brex.', 'Links', 'Syed Ali', (select id from profiles where full_name = 'Syed Ali'), null, '2026-09-30'::date, 'Q1', null
union all select 'W4', 'Service pages & location page publishing', 'Publish service pages with provided data, implement redirections, add metas, ctas, navbar/footer links update', 'Website', 'Tabish & Usman', (select id from profiles where full_name = 'Tabish Khalid'), (select id from profiles where full_name = 'Usman Ali'), '2026-09-30'::date, 'Q1', null;
